"""add is_cancelled to events

Revision ID: b4c2db70cd4a
Revises: ba269ac0e8b3
Create Date: 2025-06-22 20:11:42.045059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c2db70cd4a'
down_revision: Union[str, Sequence[str], None] = 'ba269ac0e8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_cancelled', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_events_is_cancelled'), 'events', ['is_cancelled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_is_cancelled'), table_name='events')
    op.drop_column('events', 'is_cancelled')
    # ### end Alembic commands ###
